### ISSUE TITLE
[Feature Request] Dynamically change the AI's language of the translation based on the translator selected

### ISSUE THREAD

**Issue by Touch-Night** [Touch-Night/more_translators#1]
As of now, the list of currently available languages is fixed in the program, while some translators supports more language and some less, so it is possible for user to select a language with translator not supporting it.   
There is [`get_languages()`](https://github.com/UlionTse/translators/blob/1d27ed3050bd56e90d9dfa3f83d30fde19fcf7ff/translators/server.py#L5342) function in the translators lib, so it can be done using that.

**Comment by Touch-Night** [comment]
反正没人会去选那些冷门的语言吧，翻译器也就几家好用的，等有人需要的时候再更

**Comment by Summer-FF** [comment]
兄弟，梯子不好用，谷歌的长期会停止响应。刚加载了你的翻译器，但是加载失败。
看来需要更新了兄弟。

**Comment by Touch-Night** [comment]
做出来了，虽然没有人需要
