### ISSUE TITLE
兄弟，梯子不好用，谷歌的长期会停止响应。刚加载了你的翻译器，但是加载失败。

### ISSUE THREAD

**Issue by Touch-Night** [Touch-Night/more_translators#3]
兄弟，梯子不好用，谷歌的长期会停止响应。刚加载了你的翻译器，但是加载失败。
看来需要更新了兄弟。

_Originally posted by @Summer-FF in https://github.com/Touch-Night/more_translators/issues/1#issuecomment-1855567199_

**Comment by Touch-Night** [comment]
@Summer-FF 可以提供一下详细的情况吗？加载失败的报错是什么？你是开着梯子启动的tgwebui吗？是能正常使用一段时间之后停止响应还是一开始就用不了？关掉梯子使用国内的翻译器情况怎么样呢？

**Comment by Summer-FF** [comment]
不用了，我已经搞定了，我的问题。
哈哈哈，生活就是这样。感谢兄弟回复，东西很棒！
